# Generated by Django 3.2.5 on 2021-10-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='llMobile',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resMobile',
            field=models.CharField(default=9999999999, max_length=200),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_aadhaar',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
